# Generated by Django 5.0 on 2023-12-20 20:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Studium', '0003_useranswers_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useranswers',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Studium.category'),
            preserve_default=False,
        ),
    ]
